services:
  libreoffice:
    image: lscr.io/linuxserver/libreoffice:latest
    container_name: libreoffice
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - /home/capu/shared/docker/libreoffice/config:/config
    ports:
      - 3002:3000
      - 3003:3001
    restart: unless-stopped
