services:
  it-tools:
    image: corentinth/it-tools:latest
    container_name: it-tools
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    ports:
      - 8080:80
    restart: unless-stopped
